name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run App Tests
        run: |
          echo "No tests configured yet"

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t flask-cicd-demo .
          docker tag flask-cicd-demo ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest
          
